# Note that the example .travis.yml file for child projects lives in /install.
sudo: required
language: php

php:
  - 7
  - 5.6

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"

before_install:
  - pwd
  - git remote -v
  - git checkout master
  - echo "test" > githubtest.txt
  - git add githubtest.txt
  - git commit -m "Testing travisCI commit"
  - git push origin master

install:
  # Load composer dependencies.
  - composer install
  - export PATH=$TRAVIS_BUILD_DIR/vendor/bin:$PATH

before_script:
  - mkdir $TRAVIS_BUILD_DIR/../test-project
  - cp $TRAVIS_BUILD_DIR/example.composer.json $TRAVIS_BUILD_DIR/../test-project/composer.json

script:
  - phpcs --standard=PSR2 src
  - cd $TRAVIS_BUILD_DIR/../test-project
  - composer install > output.txt 2>&1
  - grep "You are using Drupal packages that are not supported by the Drupal Security Team!" output.txt
